---
- name: Install PHP packages
  apt: name={{ item }} state=present
  with_items:
    - [ php, libapache2-mod-php, php-mcrypt, php-mysql ]

- name: copy dir.conf with new details
  copy: src=dir.conf dest=/etc/apache2/mods-enabled/dir.conf
  notify: restart apache2 service
