---
- name: Install php packages
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-mysql
    - php-fpm

- name: copy info.php file
  copy: src=info.php dest=/var/www/html/info.php
  notify: restart httpd service

- name: add the firewall for webserver
  shell: firewall-cmd --permanent --zone=public --add-service={{ item }}
  with_items:
    - http
    - https

- name: reload firewalld
  shell: firewall-cmd --reload

- name: check php info pacge using curl
  command: curl -I localhost/info.php
  register: curl_output

- name: check the site status on RedHat machine
  debug: msg="Success on RedHat machines"
  when: curl_output.stdout.find("200 OK") != -1
