---
- hosts: all
  roles:
    - { role: ../roles/apache, when: ansible_os_family == 'Debian' }
    - { role: ../roles/database, when: ansible_os_family == 'Debian' }
    - { role: ../roles/php, when: ansible_os_family == 'Debian' }
